articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('',views.index,name='index'),
    path('myinfo/',views.myinfo,name='myinfo'),
    path('project/',views.project,name='project'),
    path('skills/',views.skills,name='skills'),

]

pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from articles import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/',include('articles.urls')),
]

articles/models.py
from django.db import models

# Create your models here.

articles/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,'articles/index.html')

def myinfo(request):
    return render(request,'articles/myinfo.html')

def project(request):
    return render(request,'articles/project.html')

def skills(request):
    return render(request,'articles/skills.html')

articles/templates/articles/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  {% load static %}
  <link rel="stylesheet" href="{% static "basecss.css" %}">
  <link rel="stylesheet" href="{% static "btncss.css" %}">

</head>
<body>
  <header class="my-2">
    <div class="container my-3">
      <div class="row d-flex justify-content-center">
        <a href="{% url "articles:index" %}"><img src="{% static "logo.png" %}" alt="logo" class="mt-3" style="height: 80px;" ></a>
      </div>
      <div class="row d-flex justify-content-center" style="height:30px;">
        <nav class="navbar navbar-expand my-2">
            <div class="navbar d-block">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item mx-5">
                  <a class="nav-link nav en" aria-current="page" href="{% url "articles:myinfo" %}">My_info</a>
                </li>
                <li class="nav-item mx-5">
                  <a class="nav-link nav en" aria-current="page" href="{% url "articles:skills" %}">Skills</a>
                </li>
                <li class="nav-item mx-5">
                  <a class="nav-link nav en" aria-current="page" href="{% url "articles:project" %}">Projects</a>
                </li>
              </ul>
          </div>
        </nav>
      </div>
    </div>
  </header>
  <br><br><br>

  {% block content %}
  
  {% endblock content %}

  <footer style="height:100px; width:100%; background-color: #3f3d3c;">
    <div class="h-100 d-flex justify-content-center pt-3">
      <span class="text-white en pt-3">suhrin@naver.com</span>
    </div>
  </footer>
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</body>
</html>

articles/templates/articles/index.html
{% extends "articles/base.html" %}

{% block content %}
{% load static %}

  <div class="d-flex justify-content-center">
    <h3 class="en">Hello, World!</h3>
  </div>
  <div class="container">
    <div class="row">
      <div class="col col-12 col-lg-8 w-75 mx-auto">
        <div id="carouselExampleControls" class="carousel slide my-5 py-2" data-ride="carousel">
          <div class="carousel-inner position-relative">
            <div class="carousel-item active">
              <img src="{% static "img3.png" %} " alt="..." class="w-100">
              <p></p>
              <div class="carousel-caption p-1">
                <a href="{% url "articles:myinfo" %}"><h1 class='en text-white'>My_info</h1></a>
              </div>
            </div>
            <div class="carousel-item">
              <img src="{% static "img1.png" %}" alt="..." class="w-100">
              <div class="carousel-caption  p-1" >
                <a href="{% url "articles:skills" %}"><h1 class='en text-white'>Skills</h1></a>
              </div>
            </div>
            <div class="carousel-item">
              <img src="{% static "img2.png" %}"alt="..." class="w-100">
              <div class="carousel-caption  p-1" >
                <a href="{% url "articles:project" %}"><h1 class='en text-white'>Project</h1></a>
              </div>
            </div>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
        
      </div>
      <div class="d-none d-lg-block col col-4">
        <div class="card p-3 my-5">
          <img src="{% static "index.jpg" %}"  class="card-img-top d-inline-block m-auto w-50" alt="...">
        
          <div class="card-body d-flex flex-column">
            <h5 class="card-title text-center en">My portfolio</h5>
            <p class="card-text text-center p-0">My_info</p>
            <p class="card-text text-center p-0">Skills</p>
            <p class="card-text text-center p-0">:프로젝트에서 사용했던
              <br>프로그램 및 언어</p>
            <p class="card-text text-center p-0">Project</p>
            <p class="card-text text-center p-0">:진행했던 프로젝트</p>
            {% comment %} <a class="btn btnn p-1" href="https://www.naver.com" style="height: 50px;">
              <span>Click</span>
              <div class="dot"></div> {% endcomment %}
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>




{% endblock content %}

articles/templates/articles/myinfo.html
{% extends "articles/base.html" %}
{% load static %}
{% block content %}

<div class="container">
  <h3 class="en text-center"> My_info</h3>
  <div class="row my-3">
    <div class=" col col-12 col-md-6">
      <div class="card">
        <div class="d-flex justify-content-center">
          <img src="{% static "me.jpg" %}" class="card-img-top w-50" alt="profile">
        </div>
        <div class="card-body my-0 py-0">
          <ul class="list-group list-group-flush">
            <l1 class="list-group-item text-center pt-0 en">Minchae Hwang</l1>
            <li class="list-group-item text-center">1997.07.12</li>
            <li class="list-group-item text-center">ENFP</li>
          </ul>
        </div>
      </div>
    </div>
    <div class="col col-12 col-md-6 m-auto">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">건국대학교 응용통계학과</li>
        <li class="list-group-item">License : ADsP</li>
        <li class="list-group-item">Language Skills <br>English : TOEIC(800)</li>
      </ul>
    </div>
  </div>
  <p class="w-25"></p>

  </div>
</div>


{% endblock content %}

articles/templates/articles/project.html
{% extends "articles/base.html" %}
{% load static %}
{% block content %}

<div class="container">
  <div class="row my-3 p-2">
    <div class="col col-4">
      <img src=" {% static "bootstrap.png" %}" alt="" class='logo p-3'>
    </div>
    <div class="col col-8 d-flex">
      <div class="pt-5">
        <h4 >Bootstrap을 활용한 페이지 생성</h4>
        <p class="text-secondary mt-2">Bootstrap의 a tag의 hover를 사용해서
          navbar에 효과를 적용하여 시각적인 요소를 추가하였다.
        </p>
      </div>
    </div>
  </div>

  <div class="row m-3 p-2">
    <div class="row p-2">
      <div class="col col-8">
        <div class="pt-5">
          <h4 >R을 활용한 공유자전거 데이터 분석</h4>
          <p class="text-secondary mt-2"> Kaggle에서 제공하는 공유자전거 데이터를 활용하여
            EDA를 수행하였다. 독립변수간의 다중공선성을 확인하여 독립변수의 수를 조절하였다.
          </p>
        </div>
      </div>
      <div class="col col-4">
        <img src=" {% static "R.png" %}" alt="" class='logo p-3'>
      </div>
      
    </div>
  </div>

  <div class="row p-2">
    <div class="col col-4">
      <img src=" {% static "python.png" %}" alt="" class='logo p-3'>
    </div>
    <div class="col col-8 d-flex">
      <div class="pt-5">
        <h4 >Python을 활용한 데이터 시각화 </h4>
        <p class="text-secondary mt-2"> WordCloud와 NLTK를 사용하여 수집한 데이터의 감성분석을 진행하고, 이를 시각화하였다.
        </p>
      </div>
    </div>
  </div>
</div>


{% endblock content %}

articles/templates/articles/skills.html
{% extends "articles/base.html" %}
{% load static %}
{% block content %}

<div class="container mt-4 p-5">
  <h3 class="en text-center"> Hello, world!</h3>
  <div class="row">
    <div class="col col-12 col-md-6">
      <div class="card p-2 my-2">
        <img src="{% static "R.png" %}"  class="card-img-top d-inline-block m-auto w-50" alt="...">
        <div class="card-body d-flex flex-column">
          <h5 class="card-title text-center en">R</h5>
          <p class="card-text text-center">통계 계산과 그래픽을 위한 프로그래밍에 많이 사용된다. 전공수업을 위해 R을 사용한 EDA 및 다중회귀분석을 수행하였다.</p>
        </div>
      </div>
    </div>
    <div class="col col-12 col-md-6">
      <div class="card p-2 my-2">
        <img src="{% static "python.png" %}"  class="card-img-top d-inline-block m-auto w-50" alt="...">
        <div class="card-body d-flex flex-column">
          <h5 class="card-title text-center en">Python</h5>
          <p class="card-text text-center">통계 자료의 시각화에 뛰어나 그래프 작성에 주로 사용하였으며, 현재에는 SSAFY에서의 수업을 통해 알고리즘 문제 해결의 주된 언어로 사용하고 있다.</p>
        </div>
      </div>
    </div>
  </div>
  
</div>
  

{% endblock content %}